name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: npm install

      - name: build
        run: npm run all

      - name: test
        run: ./node_modules/.bin/jest --host=${{ secrets.FTP_IP }} --port=${{ secrets.FTP_PORT }} --username=${{ secrets.FTP_USERNAME }} --password=${{ secrets.FTP_PASSWORD }} --local=${{ secrets.FTP_LOCAL }} --remote=${{ secrets.FTP_REMOTE }}
